# 1. Assessor and analyst work

## 1.0. Rating and criteria

Please [open this document](https://static.googleusercontent.com/media/guidelines.raterhub.com/en//searchqualityevaluatorguidelines.pdf)
and study chapters 13.0-13.4. Your task will be to assess the organic answers of search engines given the same query.

## 1.1. Explore the page

For the following search engines:
- https://duckduckgo.com/
- https://www.bing.com/
- https://ya.ru/
- https://www.google.com/

Perform the same query: "**How to get from Kazan to Voronezh**".

Discuss with your TA the following:
1. Which elements you may identify at SERP? Ads, snippets, blends from other sources, ...?
2. Where are organic results? How many of them are there?

## 1.2. Rate the results of the search engine

If there are many of you in the group, assess all search engines, otherwise choose 1 or 2. There should be no less than 5 of your for each search engine. Use the scale from the handbook, use 0..4 numerical equivalents for `[FailsM, SM, MM, HM, FullyM]`. 

Compute:
- average relevance and standard deviation for each SERP element.
- [Fleiss kappa score](https://en.wikipedia.org/wiki/Fleiss%27_kappa#Worked_example) for your group. Use [this implementation](https://www.statsmodels.org/dev/generated/statsmodels.stats.inter_rater.fleiss_kappa.html).
- [Kendall rank coefficient](https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient) for some pairs in your group. Use [this implementation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kendalltau.html).

Discuss numerical results. Did you agree on the relevance? Did you agree on the rank? What is the difference?

In [5]:
import numpy as np
# example input by users
ranking_data = np.array([
    [4, 4, 4, 3, 4, 2, 2, 1, 1, 0], # assessor 1 relevance
    [...],
])

Averages ang standard deviations per item.

1) Calculate the Average (Hint use mean(axis=0) cause we care about the columns)

2) Calculate Sigma2: the Variance (mean((item - mean)**2 ))

3) Calcualte Sigma: the square root of the Variance



In [22]:
# TODO your code here
average_relevance = ...
sigma2 = ...
sigma = ...

for i in range(ranking_data.shape[1]):
    print(f" {i} relevance {average_relevance[i]:.2f} ± {sigma[i]:.3f}")



 0 relevance 3.80 ± 0.400
 1 relevance 3.80 ± 0.400
 2 relevance 4.00 ± 0.000
 3 relevance 3.60 ± 0.490
 4 relevance 3.40 ± 0.490
 5 relevance 2.20 ± 0.400
 6 relevance 1.80 ± 0.400
 7 relevance 1.00 ± 0.000
 8 relevance 1.00 ± 0.000
 9 relevance 1.00 ± 1.095


Fleiss kappa score

In [23]:
!pip install statsmodels

In [24]:
from statsmodels.stats.inter_rater import aggregate_raters, fleiss_kappa

# TODO your code here

Agreement matrix:
[[0 0 0 1 4]
 [0 0 0 1 4]
 [0 0 0 0 5]
 [0 0 0 2 3]
 [0 0 0 3 2]
 [0 0 4 1 0]
 [0 1 4 0 0]
 [0 5 0 0 0]
 [0 5 0 0 0]
 [2 2 0 1 0]]
Categories: [0 1 2 3 4]
Kappa: 0.5156081808396124


Kendall tau score is pairwise. Compare one to another.

In [53]:
from scipy.stats import kendalltau

# TODO your code here

KendalltauResult(correlation=0.8336550215650926, pvalue=0.003100607493269036)

# 2. Engineer work

You will create a bucket of URLs which are relevant for the query **"free cloud git"**. Then you will automate the search procedure using https://serpapi.com/, or https://developers.google.com/custom-search/v1/overview, or whatever.

Then you will compute MRR@10 and Precision@10.

## 2.1. Build your bucket here

In [8]:
rel_bucket = [
    "gitpod.io",
    "github.com",
    "bitbucket.org",
    "source.cloud.google.com",
    "gitlab.com",
    "sourceforge.net",
    "aws.amazon.com/codecommit/",
    "launchpad.net",
]

query = "free git cloud"

## 2.2. Relevance Assessment

The purpose of this section is to introduce a function, `is_rel`, which evaluates the relevance of a document based on its URL.

### Function Overview

**Name:** `is_rel(resp_url)`

**Arguments:**
- `resp_url`: A string representing the URL of the document we wish to assess for relevance.

**Returns:**
- A boolean value (`True` or `False`) indicating whether the document is considered relevant.

### Code Explanation

In [10]:
def is_rel(resp_url):
    pass
    # Loop through each URL our known relevant bucket
        # If the current URL is found within the provided resp_url
           # The document is relevant
    # If we've gone through the entire rel_bucket and found no matches
    # The document is not relevant

## 2.3. Automation

This section introduces a procedure to fetch search results from a search engine using an automation tool (in this case, `serpapi`). This tool allows us to programmatically obtain search results based on a query.

### Procedure Overview

1. Define the `api_key` to authenticate with the service.
2. Construct a URL endpoint that specifies the search query and other parameters.
3. Fetch the search results.
4. Parse and display the results, while also assessing their relevance.


In [14]:
# Import the requests module to send HTTP requests.
import requests

# The unique API key to access the serpapi service.
api_key = "5aff1ae53da3a991a97d770bf1991833ba30a97d68925ede4cb0003285c727ba"

# Construct the URL for fetching search results, specifying the query, language (English),
# geographic location (US), and the domain (google.com).
url = ...

# Send a GET request to the constructed URL and parse the JSON response.
js = requests.get(url).json()

# Initialize a list to store relevance indicators (1 for relevant, 0 for non-relevant).
rels = []

# Iterate over the 'organic_results' section of the response.
for result in js["organic_results"]:
    # Display the position and title of the search result.
    # Display the link (URL) of the search result.
    # Check the relevance of the link using the is_rel function and display the result.
    # Append the relevance indicator (1 or 0) to the rels list.
    print()  # Print a blank line for better visual separation.

1 6 places to host your git repository
https://opensource.com/article/18/8/github-alternatives
False

2 GitHub: Let's build from here · GitHub
https://github.com/
True

3 Gitpod: Always ready-to-code.
https://www.gitpod.io/
True

4 GitLab: The DevSecOps Platform
https://about.gitlab.com/
True

5 14 Git Hosting Services Compared | Tower Blog
https://www.git-tower.com/blog/git-hosting-services-compared/
False

6 Bitbucket | Git solution for teams using Jira
https://bitbucket.org/product
True

7 Best 13 Free Version Control Hosting Software Picks in 2023
https://www.g2.com/categories/version-control-hosting/free
False

8 Git
https://git-scm.com/
False

9 15 Best GitHub Alternatives (Free & Paid) in 2023
https://www.guru99.com/github-alternative.html
False

10 Best free git hosting? : r/git
https://www.reddit.com/r/git/comments/46t07s/best_free_git_hosting/
False



In [12]:
# Display the final list of relevance indicators for all the search results.
print(rels)

[0, 1, 1, 1, 0, 1, 0, 0, 0, 0]


## 2.4. MRR (Mean Reciprocal Rank)

MRR stands for "Mean Reciprocal Rank". It is a statistical measure used to evaluate the quality of a list of ranked items, specifically in information retrieval systems like search engines. MRR calculates the average of the reciprocal ranks of the first relevant item in the list.

### Concept:

If we have a set of ranked items, the reciprocal rank is the multiplicative inverse of the rank of the first relevant item. For example, if the first relevant item was in the 2nd position, its reciprocal rank is $\frac{1}{2}$. If no relevant items are found, then a default rank (often the length of the list plus one) is used.

The MRR is the average of the reciprocal ranks for a set of queries or lists.


In [15]:
def mrr(list_of_lists, k=10):
    # Initialize a variable to accumulate the sum of reciprocal ranks.
    r = ...
    # Iterate over each list in the list of lists.
        # If there's no relevant item in the list, use the default rank (k+1). 
        # Otherwise, compute the reciprocal rank of the first relevant item.
    # Return the mean of the accumulated reciprocal ranks.
    

In [16]:
mrr([rels]) # BTW, why do I wrap the list into additional brackets? :)

0.5

## 2.5. Precision

Precision is one of the fundamental metrics in information retrieval. It quantifies how many of the retrieved items (or documents) are relevant. Specifically, precision is defined as the ratio of relevant retrieved items to the total number of retrieved items. 

Mathematically:
$$ \text{Precision} = \frac{\text{Number of Relevant Retrieved Items}}{\text{Total Number of Retrieved Items}} $$


In the context of multiple sets of retrieved items (like multiple search queries), the mean precision is often calculated to provide an average measure across all the sets.

### Code Explanation:
## 2.5. Precision
Compute mean precision:

In [25]:
def mp(list_of_lists, k=10):
    # Initialize a variable to accumulate the sum of precisions.
    p = 0
    # Iterate over each list in the list of lists.
        # Calculate precision for the current list.
        # sum(l) gives the number of relevant items in the list, and k is the total number of items in the list.
    # Return the mean of the accumulated precisions.

In [26]:
print(mp([rels]))

0.4
